version: "3"
services:
  harvey:
    container_name: harvey
    image: harvey
    build: .
    volumes:
      - ./src:/source/src
  db:
    container_name: mongo_database
    image: mongo
    ports:
      - 9999:27017
    volumes:
      - db_data:/data/db
    restart: always

# Persistent data
volumes:
  db_data: